# Copyright 1999-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# Dependency list generated by hackport 0.9.1.0, then trimmed to the
# library/executable stanzas: the test-suite and benchmark deps (criterion,
# tasty*, lsp-test, QuickCheck) are not built here.

# No "lib": futhark is an end-user compiler, so only the executable is
# installed and nothing is registered in the GHC package database.
CABAL_FEATURES=""
inherit haskell-cabal

DESCRIPTION="Data-parallel functional array language"
HOMEPAGE="https://futhark-lang.org/"
SRC_URI="https://hackage.haskell.org/package/${P}/${P}.tar.gz"

LICENSE="ISC"
SLOT="0"
KEYWORDS="~arm64"

RDEPEND=">=dev-haskell/aeson-2.0.0.0:=
	>=dev-haskell/ansi-terminal-0.6.3.1:=
	>=dev-haskell/async-2.0:=
	dev-haskell/base16-bytestring:=
	>=dev-haskell/blaze-html-0.9.0.1:=
	>=dev-haskell/bmp-1.2.6.3:=
	>=dev-haskell/bytestring-to-vector-0.3.0.1:=
	>=dev-haskell/cmark-gfm-0.2.1:=
	dev-haskell/co-log-core:=
	dev-haskell/cryptohash-md5:=
	>=dev-haskell/diff-0.4.1:=
	>=dev-haskell/directory-tree-0.12.1:=
	>=dev-haskell/dlist-0.6.0.1:=
	dev-haskell/fgl:=
	dev-haskell/fgl-visualize:=
	>=dev-haskell/file-embed-0.0.14.0:=
	>=dev-haskell/free-5.1.10:=
	>=dev-haskell/futhark-data-1.1.4.0:=
	~dev-haskell/futhark-manifest-1.9.0.0:=
	>=dev-haskell/futhark-server-1.4.1.0:=
	>=dev-haskell/githash-0.1.6.1:=
	>=dev-haskell/half-0.3:=
	dev-haskell/haskeline:=
	>=dev-haskell/language-c-quote-0.12:=
	dev-haskell/lens:=
	>=dev-haskell/lsp-2.8.0.0:=
	>=dev-haskell/lsp-types-2.4.0.0:=
	>=dev-haskell/mainland-pretty-0.7.1:=
	>=dev-haskell/megaparsec-9.0.0:=
	dev-haskell/mwc-random:=
	>=dev-haskell/neat-interpolation-0.3:=
	dev-haskell/onetuple:=
	>=dev-haskell/parallel-3.2.1.0:=
	>=dev-haskell/prettyprinter-1.7:=
	>=dev-haskell/prettyprinter-ansi-terminal-1.1:=
	>=dev-haskell/process-extras-0.7.2:=
	>=dev-haskell/quickcheck-2.8:=
	>=dev-haskell/random-1.2.0:=
	>=dev-haskell/regex-tdfa-1.3.2:= <dev-haskell/regex-tdfa-1.4:=
	>=dev-haskell/srcloc-0.4:=
	dev-haskell/statistics:=
	dev-haskell/temporary:=
	>=dev-haskell/terminal-size-0.3:=
	>=dev-haskell/text-1.2.2.2:=
	dev-haskell/text-rope:=
	>=dev-haskell/vector-0.12:=
	>=dev-haskell/versions-6.0.0:=
	>=dev-haskell/zlib-0.7.0.0:=
	>=dev-lang/ghc-9.10.1:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.12.0.0
	dev-haskell/alex
	dev-haskell/happy
"

pkg_postinst() {
	elog "The C backend needs a C compiler. Optional backends also need:"
	elog "  OpenCL: virtual/opencl and OpenCL headers"
	elog "  CUDA:   NVIDIA CUDA toolkit"
	elog "  HIP:    ROCm"
	elog "  Python: Python, plus pyopencl for the PyOpenCL backend"
}
