# For details, see layout.conf in portage(5) and GLEP 82.
masters = gentoo
thin-manifests = true
sign-manifests = false
cache-formats = md5-dict
manifest-hashes = BLAKE2B SHA512
manifest-required-hashes = BLAKE2B
eapis-banned = 0 1 2 3 4 5 6
eapis-deprecated = 7
