# Copyright 1999-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.9.1.0

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="Collection of tools for numeric computations"
HOMEPAGE="https://github.com/haskell/math-functions"

LICENSE="BSD-2"
SLOT="0/${PV}"
KEYWORDS="~arm64"
IUSE="+system-erf +system-expm1"

RDEPEND=">=dev-haskell/data-default-class-0.1.2.0:=[profile?]
	dev-haskell/primitive:=[profile?]
	>=dev-haskell/vector-0.11:=[profile?]
	>=dev-lang/ghc-9.0.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.4.1.0
	test? ( dev-haskell/erf
		>=dev-haskell/quickcheck-2.7
		>=dev-haskell/tasty-1.2
		>=dev-haskell/tasty-hunit-0.10
		>=dev-haskell/tasty-quickcheck-0.10
		dev-haskell/vector-th-unbox )
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag system-erf system-erf) \
		$(cabal_flag system-expm1 system-expm1)
}
