# Copyright 1999-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# AUR v8-r 14.5.137 runs depot_tools + gclient to resolve DEPS, which needs
# network access during the build.  Portage only grants that in src_unpack,
# and only for live ebuilds, so we fetch each DEPS entry with git-r3 at its
# pinned commit instead.  Plain SRC_URI is not an option for these:
# chromium.googlesource.com builds +archive tarballs on demand and they are
# not byte-reproducible, so their Manifest hashes go stale immediately.
#
# Like the AUR and FreeBSD ports we link system ICU, keep V8's bundled zlib
# (the unbundle shim for it wants Chromium's //base, which V8 lacks), and
# disable Rust/Temporal plus the V8 sandbox so this links against libstdc++.
#
# Run scripts/v8-deps-pins.py to regenerate V8_DEPS on a version bump.

LLVM_COMPAT=( {20..22} )
PYTHON_COMPAT=( python3_{11..15} )

inherit check-reqs flag-o-matic git-r3 llvm-r2 ninja-utils
inherit python-any-r1 toolchain-funcs

DESCRIPTION="Google's open source JavaScript and WebAssembly engine"
HOMEPAGE="https://v8.dev/ https://github.com/v8/v8"
SRC_URI="https://github.com/v8/v8/archive/refs/tags/${PV}.tar.gz -> ${P}.tar.gz"
S="${WORKDIR}/v8-${PV}"

# Generated by scripts/v8-deps-pins.py 15.4.64
V8_DEPS=(
	"build                       https://chromium.googlesource.com/chromium/src/build.git 0aa1c79010213b38d8e4abb1499cdd84e1778685"
	"buildtools                  https://chromium.googlesource.com/chromium/src/buildtools.git 6f6a5dbf04b734214f3b1f386567d101ec9d607e"
	"tools/clang                 https://chromium.googlesource.com/chromium/src/tools/clang.git 5596c1d44f6f23d242850514d2d56daef0920bfd"
	"third_party/abseil-cpp      https://chromium.googlesource.com/chromium/src/third_party/abseil-cpp.git 435e7d977fb36fb47854a4c552c0706dad0bd7cf"
	"third_party/partition_alloc https://chromium.googlesource.com/chromium/src/base/allocator/partition_allocator.git 940e80830ad7b176f7b5ef129ca2683006fb4c7e"
	"third_party/zlib            https://chromium.googlesource.com/chromium/src/third_party/zlib.git 5eb4d7ed380f214e7a0a23c18f629048d3ba9e00"
	"third_party/jinja2          https://chromium.googlesource.com/chromium/src/third_party/jinja2.git c3027d884967773057bf74b957e3fea87e5df4d7"
	"third_party/markupsafe      https://chromium.googlesource.com/chromium/src/third_party/markupsafe.git 4256084ae14175d38a3ff7d739dca83ae49ccec6"
	"third_party/googletest/src  https://chromium.googlesource.com/external/github.com/google/googletest.git 4fe3307fb2d9f86d19777c7eb0e4809e9694dde7"
	"third_party/dragonbox/src   https://chromium.googlesource.com/external/github.com/jk-jeon/dragonbox.git beeeef91cf6fef89a4d4ba5e95d47ca64ccb3a44"
	"third_party/fp16/src        https://chromium.googlesource.com/external/github.com/Maratyszcza/FP16.git 782eea126dc5c755827be751a099eb01826175cf"
	"third_party/fast_float/src  https://chromium.googlesource.com/external/github.com/fastfloat/fast_float.git 34164f547b7df3f5d794ff67e9f885c36819ebfc"
	"third_party/simdutf         https://chromium.googlesource.com/chromium/src/third_party/simdutf f7356eed293f8208c40b3c1b344a50bd70971983"
	"third_party/highway/src     https://chromium.googlesource.com/external/github.com/google/highway.git 2607d3b5b0113992fe84d3848859eae13b3b52c1"
	"third_party/re2/src         https://chromium.googlesource.com/external/github.com/google/re2.git 972a15cedd008d846f1a39b2e88ce48d7f166cbd"
	"third_party/fadec/src       https://github.com/aengelke/fadec.git c9f78f532b9004de278489019ab2c6c28ae9746e"
	"third_party/disarm/src      https://github.com/aengelke/disarm.git 2d13d3f410a52daff1c5d8ef07d623332f372560"
	"third_party/llvm-libc/src   https://chromium.googlesource.com/external/github.com/llvm/llvm-project/libc.git 0edc5109b70f43ebd99bd4388203b19ad4af88c6"
)

LICENSE="BSD"
SLOT="0/$(ver_cut 1-2)"
# git-r3 makes this a live package, so it carries no keywords even though
# every dependency is pinned to a commit.  Needs an entry such as
# 'dev-lang/v8 **' in /etc/portage/package.accept_keywords.
KEYWORDS=""

CHECKREQS_DISK_BUILD="8G"
CHECKREQS_MEMORY="4G"

RDEPEND="dev-libs/icu:="
DEPEND="${RDEPEND}"
# Appended: git-r3 puts dev-vcs/git in BDEPEND at inherit time.
BDEPEND+="
	${PYTHON_DEPS}
	$(python_gen_any_dep 'dev-python/jinja2[${PYTHON_USEDEP}]')
	>=dev-build/gn-0.2235
	app-alternatives/ninja
	$(llvm_gen_dep '
		llvm-core/clang:${LLVM_SLOT}
		llvm-core/llvm:${LLVM_SLOT}
		llvm-core/lld:${LLVM_SLOT}
	')
	virtual/pkgconfig
"

PATCHES=(
	"${FILESDIR}/${P}-compiler-rt-paths.patch"
	"${FILESDIR}/${P}-system-clang-flags.patch"
)

pkg_setup() {
	llvm-r2_pkg_setup
	python-any-r1_pkg_setup
	check-reqs_pkg_setup
}

python_check_deps() {
	python_has_version "dev-python/jinja2[${PYTHON_USEDEP}]"
}

src_unpack() {
	default

	local dep dest uri commit
	for dep in "${V8_DEPS[@]}"; do
		read -r dest uri commit <<<"${dep}"
		git-r3_fetch "${uri}" "${commit}" "${dest}"
		git-r3_checkout "${uri}" "${S}/${dest}" "${dest}"
	done
}

src_prepare() {
	default

	# gclient normally writes this from DEPS gclient_gn_args.
	cat > build/config/gclient_args.gni <<-EOF || die
		android_ndk_version = "2@30.0.15729638"
		checkout_src_internal = false
		checkout_google_benchmark = false
	EOF

	mkdir -p build/util || die
	cat > build/util/LASTCHANGE <<-EOF || die
		LASTCHANGE=${PV}
		LASTCHANGE_YEAR=$(ver_cut 1)
	EOF

	# We link system ICU, so the only things wanted from the bundled
	# checkout are the GN files: the same shim replace_gn_files.py would
	# install, and config.gni for the icu_use_data_file arg.  Synthesizing
	# them avoids fetching 1.2GB of ICU history.
	mkdir -p third_party/icu || die
	cp build/linux/unbundle/icu.gn third_party/icu/BUILD.gn || die
	cat > third_party/icu/config.gni <<-EOF || die
		declare_args() {
		  icu_use_data_file = true
		}
	EOF
}

src_configure() {
	python_setup
	filter-lto
	tc-export AR CC CXX NM PKG_CONFIG
	export CC="${CHOST}-clang"
	export CXX="${CHOST}-clang++"
	# .gn points script_executable at a CIPD CPython we do not fetch.
	export V8_HERMETIC_PYTHON_BYPASS=1

	local myarch
	case $(tc-arch) in
		amd64) myarch=x64 ;;
		arm64) myarch=arm64 ;;
		*) die "Unsupported arch $(tc-arch)" ;;
	esac

	local gn_args=(
		"target_os=\"linux\""
		"target_cpu=\"${myarch}\""
		"is_clang=true"
		"clang_base_path=\"${EPREFIX}/usr\""
		"clang_use_chrome_plugins=false"
		"clang_version=\"${LLVM_SLOT}\""
		"use_clang_modules=false"
		"custom_toolchain=\"//build/toolchain/linux/unbundle:default\""
		"host_toolchain=\"//build/toolchain/linux/unbundle:default\""
		"is_debug=false"
		"is_component_build=true"
		"is_official_build=false"
		"dcheck_always_on=false"
		"treat_warnings_as_errors=false"
		"fatal_linker_warnings=false"
		"symbol_level=0"
		"use_custom_libcxx=false"
		"use_lld=true"
		"use_sysroot=false"
		"use_thin_lto=false"
		"use_siso=false"
		"enable_rust=false"
		"icu_use_data_file=false"
		"v8_enable_i18n_support=true"
		"v8_enable_temporal_support=false"
		"v8_enable_backtrace=true"
		"v8_enable_disassembler=true"
		"v8_enable_object_print=true"
		"v8_enable_sandbox=false"
		# Pulls in third_party/fuzztest and protobuf for test targets only.
		"v8_enable_fuzztest=false"
		"v8_use_external_startup_data=false"
		"v8_use_perfetto=false"
	)

	set -- gn gen out/Release --fail-on-unused-args --args="${gn_args[*]}"
	echo "${@}" >&2
	"${@}" || die "gn gen failed"
}

src_compile() {
	export V8_HERMETIC_PYTHON_BYPASS=1
	eninja -C out/Release d8
}

src_test() {
	out/Release/d8 -e 'print(1+1)' | grep -qx 2 || die "d8 smoke test failed"
}

src_install() {
	local libdir="${EPREFIX}/usr/$(get_libdir)"
	local so

	for so in out/Release/*.so; do
		[[ -e ${so} ]] || continue
		dolib.so "${so}"
	done

	exeinto /usr/libexec/v8
	doexe out/Release/d8
	newbin "${FILESDIR}/d8" d8
	fperms 755 /usr/bin/d8

	insinto /usr/include
	doins include/*.h
	insinto /usr/include/cppgc
	doins include/cppgc/*.h
	insinto /usr/include/cppgc/internal
	doins include/cppgc/internal/*.h
	insinto /usr/include/libplatform
	doins include/libplatform/*.h

	local pc
	for pc in v8 v8_libbase v8_libplatform; do
		sed -e "s|@PREFIX@|${EPREFIX}/usr|g" \
			-e "s|@LIBDIR@|${libdir}|g" \
			-e "s|@VERSION@|${PV}|g" \
			"${FILESDIR}/${pc}.pc.in" > "${T}/${pc}.pc" || die
		insinto "/usr/$(get_libdir)/pkgconfig"
		doins "${T}/${pc}.pc"
	done

	dodoc LICENSE
}
