# Copyright 1999-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.9.1.0

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Lift computations from the bottom of a transformer stack"
HOMEPAGE="https://github.com/mvv/transformers-base"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~arm64"
IUSE="+orphaninstances"

RDEPEND=">=dev-haskell/transformers-compat-0.6.1:=[profile?]
	>=dev-lang/ghc-9.0.2:=
	orphaninstances? ( >=dev-haskell/base-orphans-0.3:=[profile?] )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.4.1.0
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag orphaninstances orphaninstances)
}
