# Copyright 1999-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.9.1.0

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="Type-enforced sorted lists and related functions"
HOMEPAGE="https://hackage.haskell.org/package/sorted-list"

LICENSE="MIT"
SLOT="0/${PV}"
KEYWORDS="~arm64"

RDEPEND="dev-haskell/quickcheck:=[profile?]
	>=dev-lang/ghc-9.0.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.4.1.0
"
