# Copyright 1999-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.9.1.0

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="ANSI terminal backend for the »prettyprinter« package"
HOMEPAGE="https://github.com/quchen/prettyprinter"

LICENSE="BSD-2"
SLOT="0/${PV}"
KEYWORDS="~arm64"
IUSE="+text"

RDEPEND=">=dev-haskell/ansi-terminal-0.4.0:=[profile?]
	>=dev-haskell/prettyprinter-1.7.0:=[profile?]
	>=dev-lang/ghc-9.0.2:=
	text? ( >=dev-haskell/text-1.2:=[profile?] )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.4.1.0
	test? ( >=dev-haskell/doctest-0.9 )
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag text text)
}
