# Copyright 1999-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.9.1.0

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Monadic parser combinators"
HOMEPAGE="https://github.com/mrkkrp/megaparsec"

LICENSE="BSD-2"
SLOT="0/${PV}"
KEYWORDS="~arm64"
IUSE="dev"

RDEPEND=">=dev-haskell/case-insensitive-1.2:=[profile?] <dev-haskell/case-insensitive-1.3:=[profile?]
	>=dev-haskell/parser-combinators-1.0:=[profile?] <dev-haskell/parser-combinators-2:=[profile?]
	>=dev-haskell/scientific-0.3.7:=[profile?] <dev-haskell/scientific-0.4:=[profile?]
	>=dev-haskell/text-0.2:=[profile?] <dev-haskell/text-2.2:=[profile?]
	>=dev-lang/ghc-9.6.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.10.1.0
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag dev dev)
}
