# Copyright 1999-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.9.1.0

CABAL_HACKAGE_REVISION=3

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="Half-precision floating-point"
HOMEPAGE="https://github.com/ekmett/half"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~arm64"

RDEPEND=">=dev-lang/ghc-9.0.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.4.1.0
	test? ( >=dev-haskell/quickcheck-2.14.1 <dev-haskell/quickcheck-2.20
		>=dev-haskell/tasty-1.4 <dev-haskell/tasty-1.6
		>=dev-haskell/tasty-quickcheck-0.10 <dev-haskell/tasty-quickcheck-0.12 )
"
