# Copyright 1999-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.9.1.0

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="Text lines and ropes"
HOMEPAGE="https://github.com/Bodigrim/text-rope"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~arm64"
IUSE="debug"

RDEPEND=">=dev-haskell/text-1.2.3:=[profile?] <dev-haskell/text-2.2:=[profile?]
	>=dev-haskell/vector-0.11:=[profile?] <dev-haskell/vector-0.14:=[profile?]
	>=dev-lang/ghc-9.0.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.4.1.0
	test? ( dev-haskell/tasty
		>=dev-haskell/tasty-quickcheck-0.8.1 )
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag debug debug)
}
