#!/usr/bin/env python3
"""Revbump dev-lang/v8 to a new upstream tag.

Usage:
    v8-revbump.py 15.4.65
    v8-revbump.py 15.4.65 --from 15.4.64 --deploy --replace

Copies the latest (or --from) ebuild, pastes a fresh V8_DEPS block from
upstream DEPS, copies ${P}-*.patch, dry-runs those patches against the new
chromium build/ pin, then regenerates the Manifest.

Stops instead of guessing when:
  * the tag is missing
  * a NEEDED DEPS path vanished
  * DEPS grew a new unconditional git dep (override with --allow-new-deps)
  * the compiler-rt / system-clang patches no longer apply
"""

from __future__ import annotations

import argparse
import importlib.util
import re
import shutil
import subprocess
import sys
import urllib.error
import urllib.request
from pathlib import Path

V8_DEPS_RE = re.compile(
    r"# Generated by scripts/v8-deps-pins\.py [^\n]*\nV8_DEPS=\(\n.*?\n\)\n?",
    re.S,
)
PATCH_SUFFIX_RE = re.compile(r"\$\{FILESDIR\}/\$\{P\}-([^\"\s]+)\.patch")
VERSION_RE = re.compile(r"^(\d+)(?:\.(\d+))*$")
EBUILD_RE = re.compile(r"^v8-(.+)\.ebuild$")


def overlay_root() -> Path:
    return Path(__file__).resolve().parent.parent


def load_pins():
    path = Path(__file__).with_name("v8-deps-pins.py")
    spec = importlib.util.spec_from_file_location("v8_deps_pins", path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def die(msg: str, code: int = 1) -> None:
    print(f"error: {msg}", file=sys.stderr)
    raise SystemExit(code)


def log(msg: str) -> None:
    print(msg, file=sys.stderr)


def parse_pv(name: str) -> tuple[int, ...]:
    parts = []
    for chunk in name.split("_"):
        # Ignore Gentoo suffixes like _p1 / _pre; the V8 tags we ship are
        # plain dotted versions.
        if chunk.startswith(("p", "pre", "rc", "beta", "alpha")):
            break
        try:
            parts.extend(int(p) for p in chunk.split(".") if p != "")
        except ValueError:
            break
    return tuple(parts) if parts else (0,)


def find_source_ebuild(pkgdir: Path, from_version: str | None) -> Path:
    if from_version:
        path = pkgdir / f"v8-{from_version}.ebuild"
        if not path.is_file():
            die(f"source ebuild not found: {path}")
        return path

    ebuilds = []
    for path in pkgdir.glob("v8-*.ebuild"):
        match = EBUILD_RE.match(path.name)
        if match:
            ebuilds.append((parse_pv(match.group(1)), path))
    if not ebuilds:
        die(f"no v8-*.ebuild in {pkgdir}")
    ebuilds.sort()
    return ebuilds[-1][1]


def patch_suffixes(ebuild_text: str) -> list[str]:
    suffixes = PATCH_SUFFIX_RE.findall(ebuild_text)
    if not suffixes:
        die("could not find ${FILESDIR}/${P}-*.patch entries in PATCHES")
    return suffixes


def tag_exists(version: str) -> None:
    url = f"https://github.com/v8/v8/archive/refs/tags/{version}.tar.gz"
    request = urllib.request.Request(url, method="HEAD")
    try:
        with urllib.request.urlopen(request) as response:
            if response.status not in (200, 302):
                die(f"unexpected HTTP {response.status} for {url}")
    except urllib.error.HTTPError as exc:
        die(f"upstream tag {version} not found ({exc.code}): {url}")
    except urllib.error.URLError as exc:
        die(f"could not reach GitHub: {exc.reason}")


def replace_v8_deps(ebuild_text: str, block: str) -> str:
    if not V8_DEPS_RE.search(ebuild_text):
        die("source ebuild has no '# Generated by scripts/v8-deps-pins.py' V8_DEPS block")
    if not block.endswith("\n"):
        block += "\n"
    return V8_DEPS_RE.sub(block, ebuild_text, count=1)


def run_optional(cmd: list[str], cwd: Path) -> int:
    log("+ " + " ".join(cmd))
    result = subprocess.run(cmd, cwd=cwd)
    return result.returncode


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Revbump dev-lang/v8 to a new upstream tag.",
        epilog=(
            "Example: v8-revbump.py 15.4.65\n"
            "Stops if the tag is missing, a NEEDED DEPS path vanished, "
            "DEPS grew an unconditional git dep we do not fetch, or the "
            "compiler-rt / system-clang patches no longer apply."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    ap.add_argument("version", help="upstream V8 tag, e.g. 15.4.65")
    ap.add_argument(
        "--from",
        dest="from_version",
        metavar="VERSION",
        help="source ebuild version (default: newest v8-*.ebuild)",
    )
    ap.add_argument(
        "--overlay",
        type=Path,
        default=overlay_root(),
        help="overlay root containing dev-lang/v8 (default: parent of scripts/)",
    )
    ap.add_argument(
        "--allow-new-deps",
        action="store_true",
        help="continue even if DEPS grew unconditional git deps we do not fetch",
    )
    ap.add_argument(
        "--force",
        action="store_true",
        help="overwrite an existing target ebuild and its patches",
    )
    ap.add_argument(
        "--replace",
        action="store_true",
        help="remove the source ebuild and its versioned patches after success",
    )
    ap.add_argument(
        "--no-manifest",
        action="store_true",
        help="skip 'ebuild manifest'",
    )
    ap.add_argument(
        "--no-pkgcheck",
        action="store_true",
        help="skip pkgcheck scan",
    )
    ap.add_argument(
        "--deploy",
        action="store_true",
        help="rsync the package to /var/db/repos/local/dev-lang/v8",
    )
    ap.add_argument(
        "--dry-run",
        action="store_true",
        help="resolve pins and check patches, but do not write files",
    )
    args = ap.parse_args()

    if not VERSION_RE.match(args.version):
        die(f"not a dotted version: {args.version}")

    overlay = args.overlay.resolve()
    pkgdir = overlay / "dev-lang" / "v8"
    filesdir = pkgdir / "files"
    if not pkgdir.is_dir():
        die(f"missing package directory: {pkgdir}")

    source = find_source_ebuild(pkgdir, args.from_version)
    source_pv = EBUILD_RE.match(source.name).group(1)
    dest = pkgdir / f"v8-{args.version}.ebuild"
    if source.resolve() == dest.resolve() and not args.force:
        die(f"{dest.name} already is the source; pass --force to rewrite it")
    if dest.exists() and not args.force and not args.dry_run:
        die(f"{dest} already exists; pass --force to overwrite")

    log(f"source: {source.name}")
    log(f"target: {dest.name}")
    log(f"checking upstream tag {args.version}")
    tag_exists(args.version)

    pins_mod = load_pins()
    try:
        pins = pins_mod.resolve_pins(args.version)
    except urllib.error.HTTPError as exc:
        die(f"could not fetch DEPS for {args.version}: HTTP {exc.code}")
    except urllib.error.URLError as exc:
        die(f"could not fetch DEPS for {args.version}: {exc.reason}")

    if pins["missing"]:
        die(
            "these NEEDED DEPS paths are gone; update scripts/v8-deps-pins.py "
            "and the ebuild by hand:\n  " + "\n  ".join(pins["missing"])
        )
    if pins["added"]:
        listing = "\n  ".join(pins["added"])
        message = (
            "DEPS grew unconditional git dependencies we do not fetch:\n  "
            f"{listing}\n"
            "Add them to NEEDED or IGNORED in scripts/v8-deps-pins.py, or "
            "re-run with --allow-new-deps if gn/ninja do not need them."
        )
        if args.allow_new_deps:
            log("warning: " + message)
        else:
            die(message)

    log("checking each pinned remote has a usable HEAD")
    broken = pins_mod.check_remote_heads(pins["resolved"])
    if broken:
        die(
            "these remotes have no HEAD ref, which git-r3 needs to create its "
            "store:\n  " + "\n  ".join(broken) + "\n"
            "Add a GitHub (or other) mirror for them to URL_OVERRIDES in "
            "scripts/v8-deps-pins.py."
        )

    source_text = source.read_text()
    suffixes = patch_suffixes(source_text)
    source_patches = []
    for suffix in suffixes:
        path = filesdir / f"v8-{source_pv}-{suffix}.patch"
        if not path.is_file():
            die(f"source patch missing: {path}")
        source_patches.append(path)

    log("dry-running patches against the new build/ pin")
    ok, patch_log = pins_mod.check_patches(
        source_patches, pins["resolved"]["build"][1]
    )
    sys.stderr.write(patch_log)
    if not ok:
        die(
            "patches need refreshing against the new chromium build/ pin "
            "before the ebuild can be copied"
        )

    new_text = replace_v8_deps(source_text, pins["block"])
    dest_patches = [
        filesdir / f"v8-{args.version}-{suffix}.patch" for suffix in suffixes
    ]

    if args.dry_run:
        log("dry-run: would write")
        log(f"  {dest}")
        for src_p, dst_p in zip(source_patches, dest_patches):
            log(f"  {dst_p}  (from {src_p.name})")
        if not args.no_manifest:
            log(f"  ebuild {dest} manifest")
        return 0

    dest.write_text(new_text)
    log(f"wrote {dest}")
    for src_p, dst_p in zip(source_patches, dest_patches):
        if src_p.resolve() != dst_p.resolve():
            shutil.copy2(src_p, dst_p)
            log(f"wrote {dst_p}")

    if args.replace and source.resolve() != dest.resolve():
        source.unlink()
        log(f"removed {source}")
        for path in source_patches:
            if path.exists() and path.resolve() not in {
                p.resolve() for p in dest_patches
            }:
                path.unlink()
                log(f"removed {path}")

    if not args.no_manifest:
        rc = run_optional(["ebuild", str(dest), "manifest"], cwd=pkgdir)
        if rc != 0:
            die(
                "ebuild manifest failed; fix permissions/DISTDIR and re-run "
                f"'ebuild {dest} manifest'",
                code=rc,
            )

    if not args.no_pkgcheck:
        pkgcheck = shutil.which("pkgcheck")
        if pkgcheck:
            rc = run_optional([pkgcheck, "scan", str(pkgdir)], cwd=overlay)
            if rc != 0:
                die("pkgcheck scan failed", code=rc)
        else:
            log("pkgcheck not found; skipping")

    if args.deploy:
        target = Path("/var/db/repos/local/dev-lang/v8")
        if not target.parent.is_dir():
            die(f"deploy target missing: {target.parent}")
        cmd = ["rsync", "-a", "--delete", f"{pkgdir}/", f"{target}/"]
        rc = run_optional(cmd, cwd=overlay)
        if rc != 0:
            die("deploy rsync failed", code=rc)
        log(f"deployed to {target}")

    log(
        "done. emerge with:\n"
        f"  emerge -1 =dev-lang/v8-{args.version}\n"
        "(needs 'dev-lang/v8 **' in package.accept_keywords)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
