# Copyright 1999-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.9.1.0

CABAL_PN="QuickCheck"

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="Automatic testing of Haskell programs"
HOMEPAGE="https://github.com/nick8325/quickcheck"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~arm64"
IUSE="old-random +templatehaskell"

RDEPEND="dev-haskell/data-array-byte:=[profile?]
	>=dev-haskell/splitmix-0.1.0.2:=[profile?] <dev-haskell/splitmix-0.2:=[profile?]
	>=dev-lang/ghc-9.0.2:=
	old-random? ( >=dev-haskell/random-1.0.1.0:=[profile?] <dev-haskell/random-1.2.0:=[profile?] )
	!old-random? ( >=dev-haskell/random-1.2.0:=[profile?] <dev-haskell/random-1.4:=[profile?] )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.4.1.0
	test? ( templatehaskell? ( dev-haskell/hint
					dev-haskell/split ) )
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag old-random old-random) \
		$(cabal_flag templatehaskell templatehaskell)
}
