# Copyright 1999-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.9.1.0

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="A model for human colour/color perception"
HOMEPAGE="https://www.haskell.org/haskellwiki/Colour"

LICENSE="MIT"
SLOT="0/${PV}"
KEYWORDS="~arm64"

RDEPEND=">=dev-lang/ghc-9.0.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.4.1.0
	test? ( >=dev-haskell/hunit-1.4 <dev-haskell/hunit-1.7
		>=dev-haskell/quickcheck-2.5 <dev-haskell/quickcheck-2.16
		>=dev-haskell/random-1.0 <dev-haskell/random-1.3
		>=dev-haskell/test-framework-0.8 <dev-haskell/test-framework-0.9
		>=dev-haskell/test-framework-hunit-0.3 <dev-haskell/test-framework-hunit-0.4
		>=dev-haskell/test-framework-quickcheck2-0.3 <dev-haskell/test-framework-quickcheck2-0.4 )
"
