# Copyright 1999-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.9.1.0

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="A modern, easy to use, well-documented, extensible pretty-printer"
HOMEPAGE="https://github.com/quchen/prettyprinter"

LICENSE="BSD-2"
SLOT="0/${PV}"
KEYWORDS="~arm64"
IUSE="buildreadme +text"

RDEPEND=">=dev-lang/ghc-9.0.2:=
	text? ( >=dev-haskell/text-1.2:=[profile?] )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.4.1.0
	test? ( >=dev-haskell/doctest-0.9
		>=dev-haskell/quickcheck-2.5
		text? ( >=dev-haskell/pgp-wordlist-0.1
			>=dev-haskell/quickcheck-instances-0.3.17
			>=dev-haskell/tasty-0.10
			>=dev-haskell/tasty-hunit-0.9
			>=dev-haskell/tasty-quickcheck-0.8 ) )
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag buildreadme buildreadme) \
		$(cabal_flag text text)
}
