# Copyright 1999-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.9.1.0

CABAL_PN="ListLike"

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="Generalized support for list-like structures"
HOMEPAGE="https://github.com/ddssff/listlike"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~arm64"

RDEPEND=">=dev-haskell/dlist-0.8:=[profile?] <dev-haskell/dlist-1.1:=[profile?]
	>=dev-haskell/fmlist-0.9:=[profile?] <dev-haskell/fmlist-0.10:=[profile?]
	>=dev-haskell/utf8-string-1.0:=[profile?] <dev-haskell/utf8-string-1.1:=[profile?]
	>=dev-haskell/vector-0.12:=[profile?] <dev-haskell/vector-0.14:=[profile?]
	>=dev-lang/ghc-9.0.2:=
	|| ( ( >=dev-haskell/text-1.2:=[profile?] <dev-haskell/text-1.3:=[profile?] )
		( >=dev-haskell/text-2.0:=[profile?] <dev-haskell/text-2.2:=[profile?] ) )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.4.1.0
	test? ( >=dev-haskell/hunit-1.5 <dev-haskell/hunit-2
		>=dev-haskell/quickcheck-2.9 <dev-haskell/quickcheck-3
		dev-haskell/text )
"
